// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhWYXPS_zk2TbmssnS9zpaj7kCwT1FR9U',
    appId: '1:728895104988:web:3b115233b5b137ef1d9119',
    messagingSenderId: '728895104988',
    projectId: 'task-2c88e',
    authDomain: 'task-2c88e.firebaseapp.com',
    storageBucket: 'task-2c88e.firebasestorage.app',
    measurementId: 'G-R51MDYLTHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNvMVDTThm0CG4o70gRjTbsFBhvo91d08',
    appId: '1:728895104988:android:2ea3adb09d45f6f81d9119',
    messagingSenderId: '728895104988',
    projectId: 'task-2c88e',
    storageBucket: 'task-2c88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvnJ4kNe3_KNmnkq1bVrunMT6dZoRZksA',
    appId: '1:728895104988:ios:71ef18f3842ccb471d9119',
    messagingSenderId: '728895104988',
    projectId: 'task-2c88e',
    storageBucket: 'task-2c88e.firebasestorage.app',
    androidClientId: '728895104988-bov8rae0mnt60cf43p5sbg1q9jlbi7su.apps.googleusercontent.com',
    iosClientId: '728895104988-jadqj954i0hvnfnhi197st05kee9njo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvnJ4kNe3_KNmnkq1bVrunMT6dZoRZksA',
    appId: '1:728895104988:ios:71ef18f3842ccb471d9119',
    messagingSenderId: '728895104988',
    projectId: 'task-2c88e',
    storageBucket: 'task-2c88e.firebasestorage.app',
    androidClientId: '728895104988-bov8rae0mnt60cf43p5sbg1q9jlbi7su.apps.googleusercontent.com',
    iosClientId: '728895104988-jadqj954i0hvnfnhi197st05kee9njo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhWYXPS_zk2TbmssnS9zpaj7kCwT1FR9U',
    appId: '1:728895104988:web:085906ce5d2d20a41d9119',
    messagingSenderId: '728895104988',
    projectId: 'task-2c88e',
    authDomain: 'task-2c88e.firebaseapp.com',
    storageBucket: 'task-2c88e.firebasestorage.app',
    measurementId: 'G-2K72LDF59X',
  );
}
